# Generated by Django 5.2.11 on 2026-02-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0002_appointment_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reminder_Sent_At',
            new_name='reminder_sent_at',
        ),
    ]
